services:
  backend:
    image: bhargav1605/todo-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - MONGO_URI=mongodb+srv://root:Test12345@todoapp.ay5ojgc.mongodb.net/tododb?retryWrites=true&w=majority&appName=todoapp
    restart: always


  frontend:
    image: bhargav1605/todo-frontend:${BUILD_NUMBER}
    container_name: todo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
