services:
  backend:
    image: bhargav1605/todo-backend:${BUILD_NUMBER}
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always


  frontend:
    image: bhargav1605/todo-frontend:${BUILD_NUMBER}
    container_name: todo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
